version: '3.3'
services:
  ros:
    environment:
      DISPLAY: ${DISPLAY}
    network_mode: host
    volumes:
      -  /tmp/.X11-unix:/tmp/.X11-unix
    privileged: true
    container_name: 'ros2-dev'
    image: 'okumura708/ros2-dev:latest'
    devices:
      -  "/dev:/dev"
    stdin_open: true
